[audio]
enable_overdrive = true
enable_sounds = true

[bar.main]
background_opacity = 0.5
capsule = true
capsule_fill = "on_surface"
capsule_opacity = 0.099999994039535522
capsule_padding = 5.0
capsule_radius = 6.0
center = [ "clock" ]
end = [
    "tray",
    "weather",
    "screen_recorder",
    "notifications",
    "volume",
    "battery",
    "network",
    "bluetooth",
    "control-center"
]
margin_edge = 0
margin_ends = 0
position = "top"
radius = 0
scale = 1.1000000238418579
shadow = false
start = [ "workspaces", "taskbar" ]

[control_center]
sidebar = "none"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

[dock]
enabled = false
shadow = false

[idle.behavior.lock]
command = "noctalia:screen-lock"
enabled = true
timeout = 300

[idle.behavior.screen_off]
command = "noctalia:dpms-off"
enabled = false
timeout = 0

[nightlight]
enabled = true
temperature_night = 3500

[shell]
clipboard_image_action_command = "swappy -f -"
corner_radius_scale = 0.5000000074505806
font_family = "Inter"
launch_apps_as_systemd_services = true
niri_overview_type_to_launch_enabled = true
settings_show_advanced = true
telemetry_enabled = true

    [shell.animation]
    speed = 1.5

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_control_center = true
    session_placement = "centered"

    [shell.screen_corners]
    enabled = true

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "Return"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "Shift+Return"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.0

[theme]
community_palette = "ADW"
source = "community"

[wallpaper]
directory = "/home/jeffrey/Pictures/Wallpapers"
enabled = true
fill_mode = "stretch"

    [wallpaper.automation]
    enabled = false

    [wallpaper.default]
    path = "/home/jeffrey/Pictures/Wallpapers/hanged_man_tree.jpg"

    [wallpaper.last]
    path = "/home/jeffrey/Pictures/Wallpapers/hanged_man_tree.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/jeffrey/Pictures/Wallpapers/hanged_man_tree.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/jeffrey/Pictures/Wallpapers/hanged_man_tree.jpg"

[weather]
enabled = true
unit = "celsius"

[widget.audio_visualizer]
centered = false
mirrored = false

[widget.battery]
capsule = true

[widget.bluetooth]
capsule = true

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.clock]
anchor = true
capsule = true
capsule_opacity = 0.0
font_weight = 700
format = "{:%H:%M %a, %-d %b}"

[widget.control-center]
anchor = false
capsule = true

[widget.date]
capsule = true
capsule_opacity = 0.0
format = "{:%-I:%M %p - %a %-d/%-m}"

[widget.media]
hide_when_no_media = true

[widget.network]
capsule = true
show_label = false

[widget.screen_recorder]
audio_codec = "opus"
audio_source = "default_output"
color_range = "limited"
copy_to_clipboard = false
directory = "/home/jeffrey/Videos/Recordings/"
filename_pattern = "recording_%Y%m%d_%H%M%S"
frame_rate = 60
hide_inactive = false
quality = "very_high"
replay_duration = 30
replay_enabled = false
replay_storage = "ram"
resolution = "original"
restore_portal = false
script = "scripts/screen_recorder.lua"
show_cursor = true
type = "scripted"
video_codec = "h264"
video_source = "portal"

[widget.taskbar]
capsule = true
capsule_opacity = 0.0
hide_empty_workspaces = true
only_active_workspace = true
show_all_outputs = false
show_window_title = true
show_workspace_label = false
window_title_max_width = 200.0

[widget.tray]
anchor = false
drawer = true
hidden = [ "spotify-client" ]
pinned = [ "steam" ]

[widget.volume]
capsule = true
show_label = false

[widget.weather]
show_condition = false

[widget.workspaces]
capsule = false
display = "none"
hide_when_empty = true
occupied_color = "on_primary"
pill_scale = 0.75
