
# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

# See https://wiki.hyprland.org/Configuring/Keywords/
#  &  https://wiki.hyprland.org/Configuring/Binds/

# Main modifier
$mainMod = Super # super / meta / windows key

# Assign apps
$term = kitty
$editor = code
$file = dolphin
$browser = firefox
$ipc = qs -c noctalia-shell ipc call

# Window/Session actions

bind = $mainMod, Q, exec, ~/.config/scripts/close.sh
bind = $mainMod+Ctrl+Shift, Q, exec, kill -9 $(hyprctl activewindow -j | jq '.pid')
bind = $mainMod, Backspace, exec, $ipc sessionMenu toggle
bind = $mainMod, W, togglefloating,
bind = Ctrl+Alt, Return, fullscreen,

# Application shortcuts
bind = $mainMod, T, exec, $term # launch terminal emulator
bind = $mainMod, E, exec, $file # launch file manager
bind = $mainMod, F, exec, $browser # launch web browser

# Rofi menus
bind = $mainMod, A, exec, $ipc launcher toggle
bind = $mainMod, S, exec, pkill -x rofi || rofi -show ssh 
bind = $mainMod, Tab, exec, pkill -x rofi || rofi -show window
bind = $mainMod+Shift, E, exec, $file

# Audio control
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease

# Brightness control
bindel = ,XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = ,XF86MonBrightnessDown, exec, $ipc brightness decrease

# Media control
bindl  = , XF86AudioPlay, exec, $ipc media playPause
bindl  = , XF86AudioPause, exec, $ipc media playPause
bindl  = , XF86AudioNext, exec, $ipc media next
bindl  = , XF86AudioPrev, exec, $ipc media previous

# Move between grouped windows
bind = $mainMod CTRL, H, workspace, r-1
bind = $mainMod CTRL, L, workspace, r+1

# Screenshot/Screencapture
bind = $mainMod, P, exec, grim -g "$(slurp)" - | swappy -f -

# Move focused window to a relative workspace
bind = $mainMod+Ctrl+Alt, l, movetoworkspace, r+1
bind = $mainMod+Ctrl+Alt, h, movetoworkspace, r-1

# Move/Resize focused window
bindm = $mainMod, mouse:272, movewindow

# Toggle focused window split
bind = $mainMod, J, togglesplit

