#+TITLE: Doom Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle yes
#+STARTUP: fold
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

* Appearance
** Theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)

(load! "stylix-colors")

(after! doom-themes
  (custom-set-faces!
    `(default :background ,stylix-base00)
    `(fringe :background ,stylix-base00)
    `(line-number :background ,stylix-base00)
    `(line-number-current-line :background ,stylix-base01)
    `(region :background ,stylix-base02)
    `(mode-line :background ,stylix-base01)
    `(mode-line-inactive :background ,stylix-base00)
    `(solaire-default-face :background ,stylix-base00)
    `(solaire-hl-line-face :background ,stylix-base01)
    `(vertical-border :background ,stylix-base00)
    `(header-line :background ,stylix-base00)))
#+end_src

** Fonts
#+begin_src emacs-lisp
(setq doom-font      (font-spec :family "JetBrainsMono Nerd Font" :size 15)
      doom-big-font  (font-spec :family "JetBrainsMono Nerd Font" :size 25))

(after! doom-themes
  (setq doom-themes-enable-bold   t
        doom-themes-enable-italic t))
#+end_src

** line numbers
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

* Org-mode
This must be set *before* org loads — do not wrap it in =after!=.
All your org files (agenda, notes, capture targets) should live here.

#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src

* Keybindings
** Tab Naviration (Centaur Tabs)

#+begin_src emacs-lisp
(map! :g "M-H" #'centaur-tabs-backward
      :g "M-L" #'centaur-tabs-forward)
#+end_src

** Find File
#+begin_src emacs-lisp
(map! :leader
      "SPC" #'find-file)
#+end_src

** vterm-send-exc
#+begin_src emacs-lisp
(map! :after vterm
      :map vterm-mode-map
      "M-<escape>" #'vterm-send-escape)
#+end_src

** wl-paste
#+begin_src emacs-lisp
(map! "C-S-v" (cmd! (insert (shell-command-to-string "wl-paste -n"))))
#+end_src

* Evil
#+begin_src emacs-lisp
(setq evil-ex-visual-char-range nil
      evil-ex-complete-emacs-commands nil
      evil-vsplit-window-right t
      evil-split-window-below t)

(after! projectile
  (setq projectile-switch-project-action #'projectile-dired))
#+end_src
* Packages
** rpc-tramp
#+begin_src emacs-lisp
(use-package! msgpack)
(use-package! tramp-rpc)
#+end_src

* langs
** Prisma
Provides tree-sitter highlighting, LSP and formatting for =.prisma= files.

*** Dependencies
- =packages.el=: ~(package! prisma-ts-mode :recipe (:host github :repo "nverno/prisma-ts-mode"))~
- Language server: ~npm i -D @prisma/language-server~
- Formatter: ~prettier~ with ~prettier-plugin-prisma~

*** Config
#+begin_src emacs-lisp
(use-package! prisma-ts-mode
  :mode "\\.prisma\\'")
;; formatter
(after! apheleia
  (setf (alist-get 'prisma-mode apheleia-mode-alist) 'prettier)
  (setf (alist-get 'prisma-ts-mode apheleia-mode-alist) 'prettier))
;; syntax highlighter
(after! treesit
  (add-to-list 'treesit-language-source-alist
               '(prisma "https://github.com/victorhqc/tree-sitter-prisma"))
  (unless (treesit-language-available-p 'prisma)
    (treesit-install-language-grammar 'prisma)))
;; lsp
(after! lsp-mode
  (add-to-list 'lsp-language-id-configuration '(prisma-ts-mode . "prisma"))
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection '("prisma-language-server" "--stdio"))
    :activation-fn (lsp-activate-on "prisma")
    :server-id 'prisma-ls)))
(add-hook 'prisma-ts-mode-hook #'lsp-deferred)
#+end_src
** QML
Provides tree-sitter highlighting, LSP and formatting for =.qml= files.

*** Dependencies
- =packages.el=: ~(package! qml-ts-mode :recipe (:host github :repo "xhcoding/qml-ts-mode"))~
- Language server: nix pkg: ~qt6.qtdeclarative~
- Formatter: ~prettier~ with nix pkg: ~qt6.qtdeclarative~
*** Config
#+begin_src emacs-lisp
(use-package! qml-ts-mode
  :mode "\\.qml\\'")

(after! lsp-mode
  (add-to-list 'lsp-language-id-configuration '(qml-ts-mode . "qml-ts"))
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection '("qmlls" "-E"))
    :activation-fn (lsp-activate-on "qml-ts")
    :server-id 'qmlls)))

(add-hook 'qml-ts-mode-hook #'lsp-deferred)

(after! apheleia
  (setf (alist-get 'qmlformat apheleia-formatters)
        '("qmlformat" "-w" "2" "-W" "360" "-S" "--semicolon-rule" "always" filepath))
  (setf (alist-get 'qml-ts-mode apheleia-mode-alist) 'qmlformat))

(setenv "QML_IMPORT_PATH" "/nix/store/i8sw4xfclkrqdr4xv509x6ijyqvd9ld6-quickshell-2026-03-14_8aa9d8c/lib/qt-6/qml")
#+end_src
